name: art-from-audio-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - requests
  - pillow
  - pydub
  - ffmpeg
  - python-dotenv
  - pytorch
  - torchaudio
  - torchvision
  - librosa
  - datasets
  - tqdm
  - pip:
    - git+https://github.com/huggingface/transformers
    - diffusers
    - safetensors
    - accelerate
    - peft